//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks;score;b;c1;c2;c3;t1;t2;t3;t4;t5;t6
        ///1,2,3;47,628;0,943;1,169;0,994;0,970;1,119;0,893;0,911;1,000;1,000;1,000
        ///1,3,2;47,678;0,938;1,108;1,101;0,952;1,101;0,859;0,940;1,000;1,000;1,000
        ///2,1,3;46,693;0,954;1,186;1,015;0,979;1,136;0,860;0,869;1,000;1,000;1,000
        ///2,3,1;45,382;0,955;1,229;1,002;0,973;1,124;0,851;0,866;1,000;1,000;1,000
        ///3,1,2;47,049;0,946;1,121;1,045;0,986;1,124;0,821;0,958;1,000;1,000;1,000
        ///3,2,1;45,426;0,961;1,152;1,105;0,821;1,131;0,889;0,940;1,000;1,000;1,000
        ///1,2,4;51,658;1,000;1,182;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weights {
            get {
                return ResourceManager.GetString("weights", resourceCulture);
            }
        }
    }
}
